import os
import json
from modules import registry
from modules.logger import log_info, log_error

LEDGER_FILE = "memory/experience_ledger.json"

def record_experience(user_goal, initial_failure_steps, successful_steps, critique):
    """Logs a hard-fought execution trajectory into the persistent experience ledger."""
    log_info("ExperienceLearner", "Distilling workflow trial-and-error into permanent expertise...")
    
    # Ensure directory framework exists
    os.makedirs(os.path.dirname(LEDGER_FILE), exist_ok=True)
    
    lesson_prompt = f"""
You are Nova's Experience Distillation Engine. An autonomous workflow struggled but was eventually corrected. Your job is to extract a generalized rule or "lesson learned" so this mistake is never repeated.

USER GOAL: "{user_goal}"
WHAT FAILED INITIALY:
{json.dumps(initial_failure_steps, indent=2)}

WHY IT FAILED (CRITIQUE):
"{critique}"

WHAT FINALLY WORKED:
{json.dumps(successful_steps, indent=2)}

Formulate a concise, high-impact logical rule for future planners. Focus on what tool to avoid or what parameter format is required.
Respond with a single sentence. Do not include markdown, backticks, or prose.
"""
    try:
        ask_ai_func = registry.get_service("ai")
        distilled_rule = ask_ai_func(lesson_prompt).strip()
        
        # Load existing database matrix
        ledger = []
        if os.path.exists(LEDGER_FILE):
            with open(LEDGER_FILE, "r") as f:
                try:
                    ledger = json.load(f)
                except json.JSONDecodeError:
                    ledger = []
                    
        # Append structural memory packet
        ledger.append({
            "goal_keywords": list(set(user_goal.lower().split())),
            "rule": distilled_rule
        })
        
        with open(LEDGER_FILE, "w") as f:
            json.dump(ledger, f, indent=4)
            
        log_info("ExperienceLearner", f"Successfully consolidated new system rule: '{distilled_rule}'")
    except Exception as e:
        log_error("ExperienceLearner", f"Failed to commit experience to database: {e}")

def recall_relevant_lessons(user_goal):
    """Scans the ledger for rules generated by past goals sharing contextual keywords."""
    if not os.path.exists(LEDGER_FILE):
        return "No historical execution failures or lessons recorded yet."
        
    try:
        with open(LEDGER_FILE, "r") as f:
            ledger = json.load(f)
            
        goal_words = set(user_goal.lower().split())
        matched_rules = []
        
        for entry in ledger:
            # Check for keyword overlap intersections
            if goal_words.intersection(set(entry.get("goal_keywords", []))):
                matched_rules.append(f"- {entry['rule']}")
                
        if not matched_rules:
            return "No matching historical failure modes detected for this intent."
            
        return "\n".join(matched_rules)
    except Exception as e:
        log_error("ExperienceLearner", f"Failed to parse experience database logs: {e}")
        return "Error recalling past operational lessons."